url: "127.0.0.1"

collections:
  patents:
    output: true
  publications:
    output: true

defaults:
  - scope:
      path: "files/**"
    values:
      sitemap: false

analytics:
  google:
    tracking_id: "G-FGCR15Z3FK"

plugins:
  - jekyll-sitemap

exclude:
  - CHANGELOG
  - CNAME
  - LICENSE
  - README
  - tmp

sass:
  style: compressed
