version: "3.7"

services:
  jekyll_site:
    image: jekyll/jekyll:3.8
    command: ["jekyll", "serve"]
    ports:
      - "4000:4000"
    volumes:
     - type: bind
       source: .
       target: /srv/jekyll